services:
  mySql-db:
    image: mysql:8.0.43
    container_name: mySql-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    dns_search: .

  pg-db:
    image: postgres:14.18
    container_name: pg-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - pg_data:/var/lib/postgresql/data
    dns_search: .

volumes:  # ← Добавляем объявление тома
  mysql_data:
  pg_data:
